server:
  port: 8082

spring:
  application:
    name: inventory-service
  
  datasource:
    url: jdbc:h2:mem:inventorydb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  cloud:
    function:
      definition: orderEvents
    stream:
      bindings:
        orderEvents-in-0:
          destination: order-events
          content-type: application/json
          group: inventory-service-group
        inventoryResponse-out-0:
          destination: inventory-events
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092

logging:
  level:
    com.example.inventoryservice: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.SQL: DEBUG
